### PR TITLE
Feat/testing

### PR DESCRIPTION
**Pull request by sara-gudeman**
run tests from client directory by entering in terminal:
../node_modules/.bin/mocha --compilers js:babel/register --recursive

### CODE REVIEW

**Comment by erikbarzdukas** [comment]
+1

**Comment by sara-gudeman** [comment]
I need to fix one thing really quick.

**Comment by sara-gudeman** [comment]
Ok fixed everything I needed to

**Comment by LaurenJanicki** [comment]
+1

**Comment by hsadler** [comment]
Great! Thanks, Sara!

**Comment by hsadler** [comment]
+1

**Pull request merged**
