### PR TITLE
Search prod name API (fix #40)

### LINKED ISSUE #40: create "results item click" API endpoint (post MVP)
Will create an api/products server endpoint to return a product JSON object retrieved from the DB based on product_name

### PR DESCRIPTION
**Pull request by hsadler**

### CODE REVIEW

**Comment by sara-gudeman** [comment]
Looks awesome!

**Comment by sara-gudeman** [comment]
Ps I think you meant grunt not gulp in your commit messages :)

**Comment by hsadler** [comment]
whoopsie daisies.. yes, that was supposed to be "grunt removal"

**Comment by LaurenJanicki** [comment]
+1

**Pull request merged**
