### PR TITLE
Feat/search options

### LINKED ISSUE #132: Build "Search by product name" on index

### PR DESCRIPTION
**Pull request by sara-gudeman**
adds searching by product name/url closes #132

### CODE REVIEW

**Comment by sara-gudeman** [comment]
need to fix one thing real quick

**Comment by hsadler** [comment]
Just give the word when this is ready for merging. Thanks again, Sara!

**Comment by hsadler** [comment]
+1

**Comment by erikbarzdukas** [comment]
+1

**Comment by sara-gudeman** [comment]
Updated & ready for merge!

**Comment by sara-gudeman** [comment]
Wait one sec actually.

**Comment by sara-gudeman** [comment]
Okay, fully rebased and updated. Ready to merge.

**Pull request merged**
