### PR TITLE
Added gulp dev dependencies to regular dependencies

### PR DESCRIPTION
**Pull request by erikbarzdukas**
This allows npm start to rely on a gulp command

### CODE REVIEW

**Comment by hsadler** [comment]
should we be concerned by the failed Travis here?

**Comment by erikbarzdukas** [comment]
@hsadler no

**Comment by erikbarzdukas** [comment]
The travis.yml was empty and Travis was having a hissy fit about it.

**Comment by erikbarzdukas** [comment]
I'll wait a bit for +1s if you guys want, but ignore the travis output

**Comment by hsadler** [comment]
+1

**Pull request merged**
