### PR TITLE
Connect through ssl in production

### PR DESCRIPTION
**Pull request by erikbarzdukas**
Didn't realize production DB expects SSL connection. Gotta get this up there or errors are thrown.
#179

### CODE REVIEW

**Comment by erikbarzdukas** [comment]
Wait typo

**Comment by erikbarzdukas** [comment]
Fixed the typo

**Comment by hsadler** [comment]
+1

**Comment by LaurenJanicki** [comment]
+1

**Comment by sara-gudeman** [comment]
+1

**Pull request merged**
