### PR TITLE
User add tech (fix #177)

### LINKED ISSUE #177: add user ability to add technologies (ui only)
will update interface so that users can add technologies to their profile.

### PR DESCRIPTION
**Pull request by hsadler**
Added the ui

need to do the searchTech API, and then I'll finish up the client.

### CODE REVIEW

**Comment by hsadler** [comment]
please wait to merge this until Erik's scrape is done on the deployed server

**Comment by hsadler** [comment]
kk, this is ready to be merged now

**Comment by erikbarzdukas** [comment]
+1

**Comment by hsadler** [comment]
sorry, one sec... need to check something.

**Comment by hsadler** [comment]
nvmd this is good to go

**Comment by LaurenJanicki** [comment]
+1

**Pull request merged**
