### PR TITLE
Edit schema

### PR DESCRIPTION
**Pull request by erikbarzdukas**
Schema takes user's github handles and also allows for product views to be tracked.

### CODE REVIEW

**Comment by erikbarzdukas** [comment]
#182 ??

**Comment by hsadler** [comment]
ya, this should complete #182, thanks!

**Comment by hsadler** [comment]
sick +1

**Comment by erikbarzdukas** [comment]
@MisconstruedRhinoceros/owners  guise I need this to finish letting users add github links.

**Comment by sara-gudeman** [comment]
+1

**Comment by sara-gudeman** [comment]
Just let meh know when you're done & I'll merge it

**Pull request merged**
