### PR TITLE
Remove tech feature (fix #201)

### LINKED ISSUE #201: build "remove user tech" feature

### PR DESCRIPTION
**Pull request by hsadler**
```
add remove tech components
add more remove userTech client code
add users/removetech API endpoint
complete user remove tech on client
```

### CODE REVIEW

**Comment by hsadler** [comment]
hold on i have to repush.. one sec

**Comment by hsadler** [comment]
kk this is ready now

**Comment by erikbarzdukas** [comment]
+1

**Comment by sara-gudeman** [comment]
+1

**Pull request merged**
