### PR TITLE
Index skeleton (fix #27)

### LINKED ISSUE #27: build client index jsx skeleton

### PR DESCRIPTION
**Pull request by hsadler**
```
update client index, change server static file route, add basic appContainer.jsx
add index React components, add script elements for components to client index, update sample jsx
fix CDN order and script URLs
add bootstrap scaffolding to client index and navbar component
add main custom css file, update navbar, searchbar
```

### CODE REVIEW

**Comment by hsadler** [comment]
please dont merge yet. There are a couple notes and changes i want to make first. Thanks!

**Comment by hsadler** [comment]
Changes done.

**Comment by erikbarzdukas** [comment]
+2

**Comment by LaurenJanicki** [comment]
+1

**Pull request merged**
